# Generated by Django 3.2 on 2021-04-26 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 20, 43, 51, 856781, tzinfo=utc)),
        ),
    ]
