# Generated by Django 3.2 on 2021-05-02 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20210502_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 59, 27, 995625, tzinfo=utc)),
        ),
    ]
